# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bio-octopus}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ben J Woodcroft"]
  s.date = %q{2011-05-02}
  s.description = %q{Running and parsing of the protein transmembrane domain predictor octopus}
  s.email = %q{gmail.com after donttrustben}
  s.executables = ["biooctopus.rb", "biooctopus"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/biooctopus",
    "bio-octopus.gemspec",
    "lib/bio-octopus.rb",
    "lib/bio/appl/octopus.rb",
    "test/data/dummyLegacyDb",
    "test/data/dummyLegacyDb.phr",
    "test/data/dummyLegacyDb.pin",
    "test/data/dummyLegacyDb.psq",
    "test/helper.rb",
    "test/test_bio-octopus.rb"
  ]
  s.homepage = %q{http://github.com/wwood/bioruby-octopus}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Running and parsing of the protein transmembrane domain predictor octopus}
  s.test_files = [
    "test/helper.rb",
    "test/test_bio-octopus.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<bio>, [">= 1.4.1"])
      s.add_runtime_dependency(%q<fastercsv>, [">= 0"])
      s.add_runtime_dependency(%q<rio>, [">= 0"])
      s.add_runtime_dependency(%q<bio-tm_hmm>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<bio>, [">= 1.4.1"])
    else
      s.add_dependency(%q<bio>, [">= 1.4.1"])
      s.add_dependency(%q<fastercsv>, [">= 0"])
      s.add_dependency(%q<rio>, [">= 0"])
      s.add_dependency(%q<bio-tm_hmm>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<bio>, [">= 1.4.1"])
    end
  else
    s.add_dependency(%q<bio>, [">= 1.4.1"])
    s.add_dependency(%q<fastercsv>, [">= 0"])
    s.add_dependency(%q<rio>, [">= 0"])
    s.add_dependency(%q<bio-tm_hmm>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<bio>, [">= 1.4.1"])
  end
end

